### ISSUE TITLE
Store exhausted

### ISSUE THREAD

**Issue by Yorizuka** [darius/wren#2]
I have build wren using mingw on a 64 bit windows 7 computer and have gotten a executable.
But when I went to try the language out I all ways get 'Store exhausted'.
What I tried running:

```
D:\Windows\Desktop\quicky\wren-master>wren
> 1+2
Store exhausted
```

I build wren using this command: `gcc wren.c -o wren.exe -g2 -Wall -w`

Thank you for your Help & time.

**Comment by darius** [comment]
Curious -- I just ran it in almost the same kind of system (with cygwin instead of mingw). Thanks for pointing this out, though I might not be able to look into it soon.

That message occurs when the compiler runs out of memory for the compiled program. You might try increasing store_capacity to a larger number like 32768. I don't really expect that to fix the problem since the default 4096 should be more than enough to compile 1+2! (And is on my system.)

In wren.c there's an embarrassing comment "This requires that
   sizeof (unsigned char *) == sizeof (Value). Sorry!"
Perhaps with the C compiler on your system that assumption is false?

**Comment by Yorizuka** [comment]
I ran a test and it is false on my system's compiler.
I tested by adding this to the start of Wren.

```
if(sizeof (unsigned char *) == sizeof (Value)){
    printf("I'm Good\n");
  }else{
    printf("Found the problem, what now?\n");
  }
```

Do you have any suggestion on how to fix this?

**Comment by Yorizuka** [comment]
I got it work!

This is debugging code for future any reader's reference.

```
int main ()
{
  if(sizeof (unsigned char *) == sizeof (Value)){
    printf("I'm Good\n");
  }else{
    printf("Found the problem what now?\n");
    printf("Size of unsigned char: %d, Size of Value: %d\n", sizeof (unsigned char *), sizeof (Value));
  }
  
  bind ("cp", 2, a_global, 0, 0);
  compiler_ptr = the_store + sizeof (Value);
  read_eval_print_loop ();
  return 0;
}
```

The code returned this when I ran it:
```
Found the problem what now?
Size of unsigned char: 8, Size of Value: 4
```

And I fixed it by changing line 23 to:
`typedef unsigned long long int Value; // ORIGINAL: typedef int Value;`
from:
`typedef int Value;`

**Comment by Yorizuka** [comment]
Should I keep this open for others to see if they have a similar issue or close it?

Thank you for pointing me in the correct direction and your time 😄 

But I do have another issue, Now wren is failing the example check. 😠 

I'm getting problems with using functions like 'putc' I constantly get 'Unknown identifier', even when I am just copying the provided examples.

**Comment by Yorizuka** [comment]
This is the cat print out:
```
--- examples.expected   Tue Nov 30 10:33:08 2010
+++ examples.out        Fri Dec 15 13:45:22 2017
@@ -1,26 +1,26 @@
-> 1
-> 0
-> 64
-> 5
-> 7
-> > 10946
-> > > > 45
-> > Hello, world!
-0
-> > 42
-0
-> 4294967295
-0
-> > > 2007
-0
-> -1
-0
-> -2147483648
-0
-> > deadbeef
-0
-> > Unknown identifier
-> 2147483648
-0
-> > 4
->
+> 1
+> 0
+> 64
+> 5
+> 7
+> > 10946
+> Unknown identifier
+> > > 45
+> Unknown identifier
+> Unknown identifier
+> Unknown identifier
+> Unknown identifier
+> Unknown identifier
+> Unknown identifier
+> > Unknown identifier
+> Unknown identifier
+> Unknown identifier
+> Unknown identifier
+> Unknown identifier
+> Unknown identifier
+> Unknown identifier
+> Unknown identifier
+> > Unknown identifier
+> Unknown identifier
+> > 4
+>
```
